apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doc-indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rerodoc
        tier: indexer
    spec:
      containers:
      - name: rerodoc-indexer
        image: elasticsearch:2
        args: ["-Des.cluster.name=rerodoc"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9300
          name: api
        - containerPort: 9200
          name: cluster
        env:
        - name: GET_HOSTS_FROM
          value: dns
